# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: SinusBot-Support NodeJS Package

on:
  release:
    types: [created]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      
  publish-gh-packages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - continue-on-error: true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: sinusbot-scripts
          token: ${{secrets.GITHUB_TOKEN}}
      - run: echo "@sinusbot-scripts:registry=https://npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci
      - run: npm publish --registry=https://npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

#  publish-npm-packages:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Publish to NPM'
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 14
#          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm publish
#        continue-on-error: true
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPMPACKAGES}}
